name: Test Project
on: 
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # get code and download onto the runner
      - name: Get code
        uses: actions/checkout@v3
      # get nodejs installed
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      #  install all dependencies of this project
      - name: Install dependencies
        run: npm ci
      # test 
      - name: Run tests
        run: npm run test 